(function($){$.fn.cardtable=function(options){var $tables=this,defaults={headIndex:0},settings=$.extend({},defaults,options),headIndex;if(options&&options.headIndex)
headIndex=options.headIndex;else headIndex=0;return $tables.each(function(){var $table=$(this);if($table.hasClass('stacktable')){return}
var table_css=$(this).prop('class');var $stacktable=$('<div></div>');if(typeof settings.myClass!=='undefined')$stacktable.addClass(settings.myClass);var markup='';var $caption,$topRow,headMarkup,bodyMarkup,tr_class;$table.addClass('stacktable large-only');$caption=$table.find(">caption").clone();$topRow=$table.find('>thead>tr,>tbody>tr,>tfoot>tr,>tr').eq(0);$table.siblings().filter('.small-only').remove();$table.find('>tbody>tr').each(function(){headMarkup='';bodyMarkup='';tr_class=$(this).prop('class');$(this).find('>td,>th').each(function(cellIndex){if($(this).html()!==''){bodyMarkup+='<tr class="'+tr_class+'">';if($topRow.find('>td,>th').eq(cellIndex).html()){bodyMarkup+='<td class="st-key">'+$topRow.find('>td,>th').eq(cellIndex).html()+'</td>'}else{bodyMarkup+='<td class="st-key"></td>'}
bodyMarkup+='<td class="st-val '+$(this).prop('class')+'">'+$(this).html()+'</td>';bodyMarkup+='</tr>'}});markup+='<table class=" '+table_css+' stacktable small-only"><tbody>'+headMarkup+bodyMarkup+'</tbody></table>'});$table.find('>tfoot>tr>td').each(function(rowIndex,value){if($.trim($(value).text())!==''){markup+='<table class="'+table_css+' stacktable small-only"><tbody><tr><td>'+$(value).html()+'</td></tr></tbody></table>'}});$stacktable.prepend($caption);$stacktable.append($(markup));$table.before($stacktable)})};$.fn.stacktable=function(options){var $tables=this,defaults={headIndex:0,displayHeader:!0},settings=$.extend({},defaults,options),headIndex;if(options&&options.headIndex)
headIndex=options.headIndex;else headIndex=0;return $tables.each(function(){var table_css=$(this).prop('class');var $stacktable=$('<table class="'+table_css+' stacktable small-only"><tbody></tbody></table>');if(typeof settings.myClass!=='undefined')$stacktable.addClass(settings.myClass);var markup='';var $table,$caption,$topRow,headMarkup,bodyMarkup,tr_class,displayHeader;$table=$(this);$table.addClass('stacktable large-only');$caption=$table.find(">caption").clone();$topRow=$table.find('>thead>tr,>tbody>tr,>tfoot>tr').eq(0);displayHeader=$table.data('display-header')===undefined?settings.displayHeader:$table.data('display-header');$table.find('>tbody>tr, >thead>tr').each(function(rowIndex){headMarkup='';bodyMarkup='';tr_class=$(this).prop('class');if(rowIndex===0){if(displayHeader){markup+='<tr class=" '+tr_class+' "><th class="st-head-row st-head-row-main" colspan="2">'+$(this).find('>th,>td').eq(headIndex).html()+'</th></tr>'}}else{$(this).find('>td,>th').each(function(cellIndex){if(cellIndex===headIndex){headMarkup='<tr class="'+tr_class+'"><th class="st-head-row" colspan="2">'+$(this).html()+'</th></tr>'}else{if($(this).html()!==''){bodyMarkup+='<tr class="'+tr_class+'">';if($topRow.find('>td,>th').eq(cellIndex).html()){bodyMarkup+='<td class="st-key">'+$topRow.find('>td,>th').eq(cellIndex).html()+'</td>'}else{bodyMarkup+='<td class="st-key"></td>'}
bodyMarkup+='<td class="st-val '+$(this).prop('class')+'">'+$(this).html()+'</td>';bodyMarkup+='</tr>'}}});markup+=headMarkup+bodyMarkup}});$stacktable.prepend($caption);$stacktable.append($(markup));$table.before($stacktable)})};$.fn.stackcolumns=function(options){var $tables=this,defaults={},settings=$.extend({},defaults,options);return $tables.each(function(){var $table=$(this);var $caption=$table.find(">caption").clone();var num_cols=$table.find('>thead>tr,>tbody>tr,>tfoot>tr').eq(0).find('>td,>th').length;if(num_cols<3)
return;var $stackcolumns=$('<table class="stacktable small-only"></table>');if(typeof settings.myClass!=='undefined')$stackcolumns.addClass(settings.myClass);$table.addClass('stacktable large-only');var tb=$('<tbody></tbody>');var col_i=1;while(col_i<num_cols){$table.find('>thead>tr,>tbody>tr,>tfoot>tr').each(function(index){var tem=$('<tr></tr>');if(index===0)tem.addClass("st-head-row st-head-row-main");var first=$(this).find('>td,>th').eq(0).clone().addClass("st-key");var target=col_i;if($(this).find("*[colspan]").length){var i=0;$(this).find('>td,>th').each(function(){var cs=$(this).attr("colspan");if(cs){cs=parseInt(cs,10);target-=cs-1;if((i+cs)>(col_i))
target+=i+cs-col_i-1;i+=cs}else{i++}
if(i>col_i)
return!1})}
var second=$(this).find('>td,>th').eq(target).clone().addClass("st-val").removeAttr("colspan");tem.append(first,second);tb.append(tem)});++col_i}
$stackcolumns.append($(tb));$stackcolumns.prepend($caption);$table.before($stackcolumns)})}}(jQuery))